# Generated by Django 4.2.22 on 2025-06-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HexTile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("q", models.IntegerField()),
                ("r", models.IntegerField()),
                ("s", models.IntegerField()),
                ("terrain", models.CharField(default="plain", max_length=32)),
            ],
            options={
                "unique_together": {("q", "r", "s")},
            },
        ),
    ]
